### PR TITLE
Functionalities for task0 

### PR DESCRIPTION
**Pull request by jimmykimani**

### CODE REVIEW

**Comment by jimmykimani** [comment]
Exactly @kevintumbo am thinking of using dictionaries instead!

**Comment by kevintumbo** [comment]
But we were told not to use dictionaries. instead we use oop concepts

**Comment by jimmykimani** [comment]
Well my facilitator did recommend dictionaries but I'll confirm with him

**Comment by jimmykimani** [comment]
The self.office is set to None until a new object is added @kevintumbo

**Comment by kevintumbo** [comment]
@jimmykimani and after a new object is add ...what is it set to?

**Comment by kevintumbo** [comment]
@jimmykimani this is what my facilitator recommended.
You work with objects. In that case you need to work with one room as an object of class office which inherits from class Room. Class room should essentially have attributes such as (room name, room type, max-occupants, occupants). so that whenever  you store that object in a list or sth you can access all this attributes

**Comment by jimmykimani** [comment]
@kevintumbo  Since the fellow and staff sub-class inherits its properties and methods from person class they are added to an office room

**Comment by jimmykimani** [comment]
So the Class Room will be used as a blueprint for how the class office and class Room inherit properties like (room_name, room_type.....). Is that what you mean?

**Comment by kevintumbo** [comment]
That's the basic idea. yeah.

**Comment by jomomg** [comment]
In app/dojo.py 
```Python
def check_vacant_rooms(self):
        ''' checks for vacant rooms'''
       # This can be written as a list comprehension for brevity i.e
       # vacant_offices = [office for office in self.office if len(office.members) < office.capacity)]
        for office in self.office:
            if len(office.members) < office.capacity:
                if office not in self.vacant_offices:
                    self.vacant_offices.append(office)
                    self.vacant_rooms.append(office)
            # The part below is not necessary since only offices with members < 6 will ever be appended
            # to the 'vacant_offices' list. The conditional below will never be true.
            elif len(office.members) >= office.capacity:
                if office in self.vacant_offices:
                    self.vacant_offices.remove(office)
                    self.vacant_rooms.remove(office)

             # the same applies for the living_space part that follows just below the above. 
```

**Comment by RyanSept** [comment]
Good work. One recommendation, try to reduce the duplication of data. This can be done by removing the extra lists as we agreed. The Dojo class should only contain attributes that are applicable to the actual Dojo. When you have lists that are offshoots of already existing lists as attributes of the dojo, for example dojo.livingspaces and dojo.vacant_livingspaces, it's repetitive and a waste of space as they are only required during specific operations. You could perhaps have those lists generated by a function only when needed. It's not bad the way you have it it's only that it would make your code more readable and scalable, (picture a scenario where you have to move to different data structures or perhaps database columns).

**Comment by jimmykimani** [comment]
@RyanSept Thank you!, And yes I pictured this could be very reason why I had the `capacity Issue` due to duplication of data! However, I'll minimize data duplication and make my code more readable and scalable!

**Pull request merged**
